### PR TITLE
chore(buildpacks): update several buildpacks

### PR DESCRIPTION
**Pull request by mboersma**
See https://github.com/heroku/heroku-buildpack-go/compare/v65...v71
and https://github.com/heroku/heroku-buildpack-gradle/compare/v21...v23
and https://github.com/heroku/heroku-buildpack-java/compare/v51...v53
and https://github.com/heroku/heroku-buildpack-nodejs/compare/v104...v110
and https://github.com/heroku/heroku-buildpack-python/compare/v103...v109
and https://github.com/heroku/heroku-buildpack-ruby/compare/v163...v167
and https://github.com/heroku/heroku-buildpack-clojure/compare/v76...v77
and https://github.com/heroku/heroku-buildpack-scala/compare/v76...v77

### CODE REVIEW

**Comment by mboersma** [comment]
Jenkins, test this please.

**Review by bacongobbler — APPROVED** [review]

**Comment by mboersma** [comment]
Jenkins, test this please.

**Comment by mboersma** [comment]
Jenkins, test this please.

**Comment by mboersma** [comment]
Jenkins, test this please.

**Review by vdice — APPROVED** [review]

**Comment by mboersma** [comment]
Tested with all relevant deis/example-* apps.

**Pull request merged**
