### PR TITLE
feat(gcs): change signature to s3v2 based on gcs domain

### PR DESCRIPTION
**Pull request by smothiki**
add support for GCS in compat mode

### CODE REVIEW

**Comment by smothiki** [comment]
closes https://github.com/deis/slugbuilder/issues/31

**Comment by arschles** [comment]
@smothiki when this is ready for review, can you please add some testing instructions and add the `awaiting review` label?

**Comment by smothiki** [comment]
Sure

**Comment by smothiki** [comment]
Testing instructions
- use the following images smothiki/workflow:v1.6 and smothiki/builder:v1.3 for workflow and builder.
- turn on interoperabiltiy mode GCS storage.
- change credentials in deis-minio-secret-user
- set the below env variables in builder RC

```
            - name: "DEIS_OUTSIDE_STORAGE"
              value: "storage.googleapis.com"
            - name: "BUCKET"
              value: "<what ever unique bucket>"

```

**Comment by bacongobbler** [comment]
did not manually test but code LGTM.

**Comment by arschles** [comment]
@smothiki I'll test this shortly

**Comment by arschles** [comment]
@smothiki when I follow the testing instructions that you posted, the builder fails to start completely:

``` console
ENG000656:builder aaronschlesinger$ kd get pod -w
NAME                  READY     STATUS    RESTARTS   AGE
deis-builder-rmw4h    0/1       Running   1          1m
deis-database-3l5tc   1/1       Running   1          7m
deis-minio-knxwy      1/1       Running   0          7m
deis-registry-f2ydl   1/1       Running   3          7m
deis-router-xzrss     1/1       Running   0          7m
deis-workflow-vomc3   1/1       Running   0          40s
```

Builder logs include the following:

``` console
Healthcheck error listing buckets (The provided security credentials are not valid.)
```

Is it possible that the builder cannot talk to GCS? I tested that during https://github.com/deis/builder/pull/223, but it doesn't appear to work now.

**Comment by smothiki** [comment]
> Is it possible that the builder cannot talk to GCS? 

Minio-go sdk talks to GCS . You should check your access key or secret key . is it possible to try with the below minio-user secret. 

```
apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: deis
  labels:
    heritage: deis
type: Opaque
data:
  access-key-id: R09PR0w1UlJYRUhYSDMySFlLNkE=
  access-secret-key: U0FLZytBWE5IalBWa21TWUxXN2pIcXE4clpnMUY2ejN4b3ZKL2cvawk=
```

**Comment by arschles** [comment]
@smothiki sorry about that, I forgot to base64-encode my GCS credentials. Slug builds worked against my GCS bucket. LGTM

**Pull request merged**
