### PR TITLE
chore(buildpacks): update heroku-buildpack-nodejs to v88

### PR DESCRIPTION
**Pull request by mboersma**
See https://github.com/heroku/heroku-buildpack-nodejs/compare/v87...v88

### CODE REVIEW

**Comment by mboersma** [comment]
I tested this with [example-nodejs](https://github.com/deis/example-nodejs).

**Comment by jchauncey** [comment]
how do you build and test this?

**Comment by mboersma** [comment]
> how do you build and test this?

Sorry, I should have put those instructions in here. I've already tested it manually--here's what I did:
1. build a custom deis/slugbuilder with this change and push it to an accessible Docker registry
2. build a custom deis/builder that references the above image as `slugBuilderImage` in pkg/gitreceive/k8s_util.go (or just implement deis/builder#66 and be a hero), then push it to an accessible Docker registry
3. modify the deis-builder-rc.yaml to reference the above image
4. kill the deis-builder RC and recreate it from the above manifest
5. register a user and `git push` the [example-nodejs-express](https://github.com/deis/example-nodejs-express) app, do some scaling and `config:set` as well

**Comment by jchauncey** [comment]
@mboersma this is ready

**Pull request merged**
