### PR TITLE
chore(Dockerfile): update version

### PR DESCRIPTION
**Pull request by arschles**
Fixes part of https://github.com/deis/workflow/issues/97

cc/ @mboersma

### CODE REVIEW

**Comment by slack** [comment]
Actually, do we want this to be `2.0.0-dev`?

**Comment by arschles** [comment]
I'm not sure what the convention is so I left this hanging out w/o a milestone. Happy to go with `2.0.0-dev`, and can make that change in other repos as well.

**Comment by slack** [comment]
Informal survey of all the deis projects indicates that `-dev` is the convention. Let's go with that, we can update to `alpha1` when we cut that release.

**Comment by arschles** [comment]
@slack updated to `2.0.0-dev`

**Pull request merged**
