### PR TITLE
feat(mutable): add support for immutable builds

### LINKED ISSUE #36: Publish immutable artifact tags + canary version to Docker registries
We want to have the ability to have deis/charts reference a specific immutable image which will enable us better traceability on issues that come into various components.

What we've done with efforts in other repositories is publish a version:
- `git-[short sha]` that will never be overwritten
- `canary` that will move to reference the latest version available of a component

Examples of the easiest way to roll this change out can be seen in deis/workflow#487, deis/builder#246, and deis/workflow-manager#11

### PR DESCRIPTION
**Pull request by smothiki**
closes https://github.com/deis/slugbuilder/issues/36

### CODE REVIEW

**Comment by smothiki** [comment]
ping @mboersma @arschles @sgoings

**Comment by krancour** [comment]
Should the commit and PR title actually read "add support for _immutable_ build"?  Apart from that, LGTM.

**Comment by smothiki** [comment]
@vdice @sgoings updated travis yaml PTAL

**Comment by vdice** [comment]
@smothiki code LGTM.  Just be sure a TravisCI job that merges a commit to master properly kicks off sibling jenkins job (just in case the secure url happened to be malformed)

**Pull request merged**
